In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
TRUE_PATH = "../data/raw/True.csv"
FAKE_PATH = "../data/raw/Fake.csv"

In [3]:
fakeNews = pd.read_csv(FAKE_PATH)
trueNews = pd.read_csv(TRUE_PATH)

In [4]:
trueNews.head(10)

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"
5,"White House, Congress prepare for talks on spe...","WEST PALM BEACH, Fla./WASHINGTON (Reuters) - T...",politicsNews,"December 29, 2017"
6,"Trump says Russia probe will be fair, but time...","WEST PALM BEACH, Fla (Reuters) - President Don...",politicsNews,"December 29, 2017"
7,Factbox: Trump on Twitter (Dec 29) - Approval ...,The following statements were posted to the ve...,politicsNews,"December 29, 2017"
8,Trump on Twitter (Dec 28) - Global Warming,The following statements were posted to the ve...,politicsNews,"December 29, 2017"
9,Alabama official to certify Senator-elect Jone...,WASHINGTON (Reuters) - Alabama Secretary of St...,politicsNews,"December 28, 2017"

In [5]:
fakeNews.head(10)

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"
5,Racist Alabama Cops Brutalize Black Boy While...,The number of cases of cops brutalizing and ki...,News,"December 25, 2017"
6,"Fresh Off The Golf Course, Trump Lashes Out A...",Donald Trump spent a good portion of his day a...,News,"December 23, 2017"
7,Trump Said Some INSANELY Racist Stuff Inside ...,In the wake of yet another court decision that...,News,"December 23, 2017"
8,Former CIA Director Slams Trump Over UN Bully...,Many people have raised the alarm regarding th...,News,"December 22, 2017"
9,WATCH: Brand-New Pro-Trump Ad Features So Muc...,Just when you might have thought we d get a br...,News,"December 21, 2017"

In [6]:
print(f'Shape of trueNews - {trueNews.shape}')
print(f'Shape of fakeNews - {fakeNews.shape}')

Shape of trueNews - (21417, 4)
Shape of fakeNews - (23481, 4)

In [7]:
trueNews.info()

<class 'pandas.DataFrame'>
RangeIndex: 21417 entries, 0 to 21416
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   title    21417 non-null  str
 1   text     21417 non-null  str
 2   subject  21417 non-null  str
 3   date     21417 non-null  str
dtypes: str(4)
memory usage: 669.4 KB

In [8]:
fakeNews.info()

<class 'pandas.DataFrame'>
RangeIndex: 23481 entries, 0 to 23480
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   title    23481 non-null  str
 1   text     23481 non-null  str
 2   subject  23481 non-null  str
 3   date     23481 non-null  str
dtypes: str(4)
memory usage: 733.9 KB

# DATA CLEANING

In [9]:
fakeNews.duplicated().sum()

np.int64(3)

In [10]:
trueNews.duplicated().sum()

np.int64(206)

In [11]:
# Dropping the duplicate rows 

trueNews = trueNews.drop_duplicates().reset_index(drop=True)
fakeNews = fakeNews.drop_duplicates().reset_index(drop=True)

print(f'Shape of trueNews - {trueNews.shape}')
print(f'Shape of fakeNews - {fakeNews.shape}')

Shape of trueNews - (21211, 4)
Shape of fakeNews - (23478, 4)

In [12]:
# Dropping the exact title and text

trueNews = trueNews.drop_duplicates(subset=['title','text']).reset_index(drop=True)
fakeNews = fakeNews.drop_duplicates(subset=['title','text']).reset_index(drop=True)

In [13]:
trueNews = trueNews[['title','text']]
fakeNews = fakeNews[['title','text']]

In [14]:
# Dropping the exact title as the text are different due to typo errors in trueNews
# Retain the exact text as they are less and tell different styles of title in trueNews

trueNews = trueNews.drop_duplicates(subset=['title']).reset_index(drop=True)

In [15]:
# Many rows of the fakeNews contains empty text so removing them

print((fakeNews["text"].str.strip() == "").sum())
fakeNews = fakeNews[fakeNews["text"].str.strip() != ""].reset_index(drop=True)

446

In [16]:
# Dropping the rows with duplicate title or duplicate text as the other has just typo errors

print(f"No of duplicate titles - {fakeNews['title'].duplicated().sum()}")
print(f"No of duplicate texts - {fakeNews['text'].duplicated().sum()}")

fakeNews = fakeNews.drop_duplicates(subset=['title']).reset_index(drop=True)
fakeNews = fakeNews.drop_duplicates(subset=['text']).reset_index(drop=True)

No of duplicate titles - 5
No of duplicate texts - 9

In [17]:
# Some rows in fakeNews contain just a single word which is mostly a link, so removing them

print(f"No of single word texts - {(fakeNews['text'].str.split().str.len() <= 1).sum()}")
print(f"No of single word titles - {(fakeNews['title'].str.split().str.len() <= 1).sum()}")

fakeNews = fakeNews[(fakeNews["text"].str.split().str.len() > 1) & (fakeNews["title"].str.split().str.len() > 1)].reset_index(drop=True)

No of single word texts - 59
No of single word titles - 6

### Almost all the text in trueNews begins with "CITY_NAME (Reuters) - " . So I will remove all these starting phrases.

In [18]:
trueNews['text'] = (trueNews['text'].str.split('-',n=1).str[-1].str.lstrip())

In [19]:
trueNews['text'].head(20)

0     The head of a conservative Republican faction ...
1     Transgender people will be allowed for the fir...
2     The special counsel investigation of links bet...
3     Trump campaign adviser George Papadopoulos tol...
4     President Donald Trump called on the U.S. Post...
5     The White House said on Friday it was set to k...
6     President Donald Trump said on Thursday he bel...
7     While the Fake News loves to talk about my so-...
8     Together, we are MAKING AMERICA GREAT AGAIN! b...
9     Alabama Secretary of State John Merrill said h...
10    Alabama officials on Thursday certified Democr...
11    The new U.S. tax code targets high-tax states ...
12    Vanity Fair, which looks like it is on its las...
13    “On 1/20 - the day Trump was inaugurated - an ...
14    A man claiming to be the person who delivered ...
15    A lottery drawing to settle a tied Virginia le...
16    A Georgian-American businessman who met then-M...
17    Based on the fact that the very unfair and unp...
18    A U.S. appeals court in Washington on Tuesday ...
19    A gift-wrapped package addressed to U.S. Treas...
Name: text, dtype: object

### Most of the fakeNews data contain image / video sources in the end in their text which in uncommon in trueNews. So I will remove them.

In [20]:
fakeNewsText = fakeNews['text']
fakeNewsText.info()

<class 'pandas.Series'>
RangeIndex: 17388 entries, 0 to 17387
Series name: text
Non-Null Count  Dtype
--------------  -----
17388 non-null  str
dtypes: str(1)
memory usage: 136.0 KB

In [21]:
for i in range(len(fakeNewsText)):
    if (fakeNewsText[i])[-1] == '.':
        fakeNewsText[i] = (fakeNewsText[i])[:-1]

In [22]:
import re

for i in range(50):
    article = fakeNewsText[i]
    parts = re.split(r'[?.!]',article)
    parts = [p.strip() for p in parts if p.strip()]
    print(parts[-1])

Photo by Andrew Burton/Getty Images
Photo by Win McNamee/Getty Images
Photo by Spencer Platt/Getty Images
Photo by Joe Raedle/Getty Images
Photo by Christopher Furlong/Getty Images
Featured image via David McNew/Stringer/Getty Images
Photo by Zach Gibson   Pool/Getty Images
Featured image via Chris Kleponis/Pool/Getty Images
Featured image via BRENDAN SMIALOWSKI/AFP/Getty Images
Featured image via Al Drago-Pool/Getty Images
Featured image via Rob Kim/Getty Images
Featured image via Mark Wilson/Getty Images
Photo by Chip Somodevilla/Getty Images
Featured image via video screen capture
Photo by Ralph Orlowski/Getty Images for Burda Media
Featured image via Alex Wong/Getty Images
Image via Twitter
Photo by Ann Heisenfelt/Getty Images
Watch the video below:Featured image via Scott Olson/Getty Images
Photo by Ann Heisenfelt/Getty Images
Featured image via Alex Wong/Getty Images
Featured image via screen capture
Brown/Getty Images
Featured image via Justin Sullivan/Getty Images
Image via screen capture
Featured image via Alex Wong/Getty Images
com/wFgDkvzEhT  The Reagan Battalion (@ReaganBattalion) December 10, 2017Featured image via Drew Angerer/Getty Images
co/SIoAxatCjp  Sarah Sanders (@SarahHuckabee) November 3, 2016Image via screen capture
Photo by Drew Angerer/Getty Images
Photo by Jeff Vinnick/Getty Images
Watch the video of the remarks of the Scott family below: Featured image via Grace Beahm-Pool/Getty Images
Featured image via Andrew Burton/Getty Images
Watch Trump s announcement here:Featured image via Chip Somodevilla/Getty Images
Featured image by Andrew Burton/Getty Images
Image via screen capture
Featured image Drew Angerer/Getty Images
Featured image via Scott Olson/Getty Images
Featured image via Win McNamee/Getty Images
Featured image via William Thomas Cain/Getty Images
Photo by Mark Wilson/Getty Images
Photo by Tom Pennington/Getty Images
, and then to Trump himself   and then Hillary will really have the last laugh
Photo by Chip Somodevilla/Getty Images
Photo by Steve Pope/Getty Images
Featured image via Chip Somodevilla/Getty Images
Photo by David Becker/Getty Images
Featured image via Chip Somodevilla/Getty Images
Featured image via Thomas Lohnes/Getty Images
Watch the amazing ad here:Featured image via Bill Pugliano/Getty Images
Featured image via Win McNamee/Getty Images

In [23]:
# Removing the sources at last in the fakeNewsText

for i in range(len(fakeNewsText)):
    article = fakeNewsText[i]
    article = re.sub(r'[?.!][^?.!]*$','',article)
    article = article.strip()
    fakeNewsText[i] = article + '.'

In [24]:
for i in range(50):
    article = fakeNewsText[i]
    parts = re.split(r'[?.!]',article)
    parts = [p.strip() for p in parts if p.strip()]
    if parts:
        print(parts[-1])

70-year-old men don t change and now he s a year older
It s a badly scripted reality TV show
It can t be repeated enough
Tim Peterson (@timrpeterson) December 28, 2017Donald Trump is obsessed with Obama that his name was even in the coding of his website while he played golf again
Amen to that
Please share far and wide, and stay tuned to Addicting Info for further updates
It s still a lie, though
Let s hope that more indictments from Robert Mueller are on their way as we speak
We re already well on our way
This ad is vile
We just have to survive the present to get there
It is the height of arrogance and insult to imply that there are no struggling families in either of those two states
Funny how that works
Freudian slip
It s a heist
I am equally sure that he also knows that Trump is an international embarrassment and a crazy man who never should have been allowed anywhere near the White House
co/65FhbQHuV4 #Disney #Trump #JonVoight  David Schmid (@DavidSchmid1) December 19, 2017We re pretty sure Disney is trolling Trump
Trump
Until then, we ll have to stick to  Weekend Update  and the rest of SNL, and hope for the best
History will not be kind to you
Anyway, Happy Holidays Merry Christmas from Donald Trump, everyone
Sad to say, but true
Featured image via Frederick M
Get a fifty state strategy going so we can blow the GOP outta the water in 2018
Yeah, Trump, you called her a whore
Every last one of you
twitter
co/SIoAxatCjp  Sarah Sanders (@SarahHuckabee) November 3, 2016Image via screen capture
Right-wing Alabama evangelicals seem to take no issue with Moore s scandalous past, which includes hating Muslims, the LGBTQ community, and allegedly creeping up on young girls
Trump and Moore support each other
Hopefully this sets a precedent, and helps us turn a corner toward the arc of justice
While the Republicans in the Cabinet and Congress may not yet be ready to take this step, it is out there
No wonder they re mostly Republicans
By making such a move, for such purely personal reasons, Trump is proving, once again, that he is not fit to be president of a condo association, much less of the United States
Image via screen capture
But, hey   better a pedophile than a Democrat, right
Besides, let s face it   the GOP writ large showed America and the world what they stand for when they elected Donald Trump
If he has this lack of concern for his own wellbeing, then what does it say of his risk-assessment abilities
Probably just should have kept quiet at 74 and hoped for things to improve organically
Because, it s not Hillary Clinton who will be locked up, after all
You ll find integrity and honesty at FBI headquarters and not at 1600 Penn Ave right now  Eric Holder (@EricHolder) December 3, 2017What the FBI agents are saying is that Donald Trump is fake news
It will go from Flynn, to Pence, to Trump Jr
Nailed it
Shorter version: Trump just tripped over his own little d*ck and presented exhibit A for trial because he obstructed justice
Now, they are very likely to rue the day they ever heard the name Donald Trump
On top of that, just after Flynn was forced to resign, Trump called him a  wonderful man  who was treated unfairly by the media
We hope you like orange jumpsuits
We can hope
I d say so
It s time for Republicans to stop being cowards and remove Trump

### Many of the titles in fakeNews contain words like WATCH, VIDEO, TWEET which are enclosed in brackets. All the brackets words are just emphasising and are not present in trueNews. I will remove the words in bracket

In [25]:
fakeNewsTitle = fakeNews['title']
fakeNewsTitle.info()

<class 'pandas.Series'>
RangeIndex: 17388 entries, 0 to 17387
Series name: title
Non-Null Count  Dtype
--------------  -----
17388 non-null  str
dtypes: str(1)
memory usage: 136.0 KB

In [26]:
for i in range(len(fakeNewsTitle)):
    title = fakeNewsTitle[i]
    newTitle = re.sub(r"\s?\([^)]","",title)
    fakeNewsTitle[i] = newTitle
    fakeNewsTitle[i].lstrip()

### The fakeNewsTitle contains many words in full capital like BREAKING, ANNOYED, ENOUGH and many more. These are not abbreviations. These are just added to emphasise, these emphasis are not present in trueNews and is a direct source to detect fake news. So I will modify these capital words.

### It is difficult to select these capital words in the whole fake news dataset, and then classify whether they are used for emphasis or are abbreviations. So I will use a trick. I will make a list of capital words in true news titles. They are mostly abbreviations. And then use this list to make all other capital words to lowercase in the fake news dataset.

### Another observation is that all the words in the title of fake news dataset start with capital letter. So I will first make all the words to start with lowercase (except abbreviations list) and then make the first letter of the title to uppercase.

In [27]:
trueNewsTitle = trueNews['title']

abbreviations = []
names = []

for i in range(len(trueNewsTitle)):
    title = trueNewsTitle[i]
    words = title.split()
    abbreviations.extend([word for word in words if word.isupper()])


for i in range(len(trueNewsTitle)):
    title = trueNewsTitle[i]
    words = title.split()
    for word in words[1:]:
        if word[0].isupper() and not word.isupper():
            names.append(word)

abbreviations = list(set(abbreviations))
names = list(set(names))

print(f'No of abbreviations - {len(abbreviations)}')
print(f'No of names - {len(names)}')

No of abbreviations - 498
No of names - 4378

In [28]:
for i in range(len(fakeNewsTitle)):
    title = fakeNewsTitle[i]
    words = title.split()
    for j in range(len(words)):
        if words[j] == 'A' or (words[j] not in names and words[j] not in abbreviations):
            words[j] = words[j].lower()
            
    fakeNewsTitle[i] = " ".join(words)

In [29]:
# Now making the starting letter to uppercase

for i in range(len(fakeNewsTitle)):
    title = fakeNewsTitle[i]
    if title:
        title = title[0].upper() + title[1:]
    fakeNewsTitle[i] = title

In [30]:
for i in range(50):
    print(fakeNewsTitle[i])

Donald Trump sends out embarrassing New year’s Eve message; This is disturbing
Drunk bragging Trump staffer started Russian collusion investigation
Sheriff David clarke becomes an Internet joke for threatening to poke People ‘in The eye’
Trump Is so obsessed he even has Obama’s name coded into his websitemages)
Pope Francis just called out Donald Trump during his Christmas speech
Racist Alabama cops brutalize Black Boy While he Is In handcuffsraphic images)
Fresh off The golf course, Trump lashes out At FBI Deputy Director and james Comey
Trump said Some insanely racist stuff Inside The Oval Office, and witnesses back It up
Former CIA Director slams Trump Over UN bullying, openly suggests he’s acting like a dictatorweet)
Watch: brand-new pro-trump ad features so much a** kissing It Will Make you sick
Papa john’s founder retires, figures out racism Is bad for Business
Watch: Paul Ryan just told us he doesn’t care About struggling families Living In Blue States
Bad News for Trump — Mitch McConnell Says No to repealing Obamacare In 2018
Watch: Lindsey Graham trashes Media for portraying Trump As ‘kooky,’ forgets his own words
Heiress to disney empire knows GOP scammed us – shreds them for Tax Bill
Tone deaf Trump: congrats Rep. Scalise on losing weight After you almost died
The Internet brutally mocks disney’s New Trump robot At hall Of presidents
Mueller spokesman just f-cked up Donald Trump’s Christmas
Snl hilariously mocks accused Child molester Roy Moore for losing al Senate raceideo)
Republican Senator gets dragged for going After Robert Mueller
In a heartless rebuke to victims, Trump invites NRA to Xmas Party on sandy hook anniversary
Ky GOP State Rep. commits suicide Over allegations he molested a teen girletails)
Meghan McCain tweets The Most amazing response to doug jones’ win In deep-red Alabama
CNN calls it: a Democrat Will represent Alabama In The Senate for The First Time In 25 years
White House: It wasn’t sexist for Trump to slut-shame Sen. Kirsten gillibrandideo)
Despicable Trump suggests female Senator would ‘do anything’ with him for campaign moneyweet)
Accused Child molesting Senate Candidate Roy Moore sides with Putin Over reaganideo)
Watch: Fox host calls for a ‘cleansing’ Of The FBI, and to arrest everyone investigating Trump
Liberal Group trolls Trump At Roy Moore rally In The best possible wayideo)
Don Jr. tries to mock Al franken’s resignation, backfires immediately
Breaking: cop finally gets his due, walter scott’s killer sentenced to prisonetails)
Watch: Is This proof Trump Is unfit for service?
Trump completely screws The Middle East Peace process, just another Wednesday for him
Trump only cares About Trump; Why he Is recognizing Jerusalem Today
Watch: Trump supporting coal CEO upset Trump Is wiping out ‘thousands’ Of coal mining jobs
Sitting GOP Senator has had enough, donates to Alabama Democrat for senatemage)
Republican National committee: better a pedophile than a Democrat In The U.S. Senate
Donald Trump’s eating habits Could Be dramatically affecting his wellbeing and our Safety
John McCain wanted another 74 Twitter followers, but his Plan backfired miserablyweets)
This sarah Huckabee Sanders Tweet About attacking The FBI hasn’t aged well
FBI agents destroy Donald Trump After he attacks The Agency and james Comey
‘ghost Of witness flipped’: hilarious snl skit takes Trump into his own private holiday hellideo)
Leaked email proves Trump officials aware Russia had ‘thrown The USA election’ to Trump
Trump just admitted he knew Flynn lied to The FBI before he asked Comey to drop The investigation
Watch This awesome mashup of Michael Flynn leading The ‘lock her up’ chant As he goes off to courtideo)
White House panics knowing Flynn Is going to take them down
Breaking: Michael Flynn cracks – Will testify to Mueller against Trump himself
Trump gets an epic f**ck you From Britain Over his White supremacist retweets
This hilarious campaign ad shows voters How they Can avoid scandalous elected officials
Joe scarborough: It’s Not our imagination – Trump really Is losing his mindideo)

Most of the noise in fakeNewsTitle is removed. Now I will modify some words by manual inspection which are difficult to select.

In [31]:
# Listing all the words whose first letter is uppercase 
# I will change these to lowercase if its a common word where uppercase is not required

firstLetterCapital = []

for i in range(len(fakeNewsTitle)):
    title = fakeNewsTitle[i]
    words = title.split()
    for word in words[1:]:
        if word[0].isupper() and not word.isupper():
            firstLetterCapital.append(word)

firstLetterCapital = list(set(firstLetterCapital))
print(len(firstLetterCapital))
#print(firstLetterCapital)

1583

In [32]:
fakeNames = ['Research','Child','Now','See','Maybe','Is','In','At','Says']

for i in range(len(fakeNewsTitle)):
    title = fakeNewsTitle[i]
    words = title.split()
    for j in range(len(words)):
        if words[j] in fakeNames:
            words[j] = words[j].lower()
            
    fakeNewsTitle[i] = " ".join(words)

In [33]:
fakeNewsTitleWords = []

for i in range(len(fakeNewsTitle)):
    title = fakeNewsTitle[i]
    words = title.split()
    fakeNewsTitleWords.extend(words)

fakeNewsTitleWords = sorted(list(set(fakeNewsTitleWords)))
print(len(fakeNewsTitleWords))
for i in range(50):
    print(fakeNewsTitleWords[i])

33950
#1
#100
#100.2
#101
#102
#103
#104
#105
#106
#108
#109
#10:
#110
#111
#112
#113
#114
#115
#116
#117
#118
#119
#11:
#120
#121
#122
#123
#124
#125
#126
#127
#128
#129
#13
#130
#131
#132
#133
#134
#135
#136
#137
#138
#13:
#141
#149
#152
#153
#154
#159

In [34]:
trueNewsTitleWords = []

for i in range(len(trueNewsTitle)):
    title = trueNewsTitle[i]
    words = title.split()
    trueNewsTitleWords.extend(words)

trueNewsTitleWords = sorted(list(set(trueNewsTitleWords)))

print(len(trueNewsTitleWords))
for i in range(50):
    print(trueNewsTitleWords[i])

22861
"Access
"Brexit
"Chennai
"I
"It
"Madame
"Make
"Mischievous"
"Nobody
"Rohingya"
"SEE
"The
"Top
"You
"a
"absolute
"absolutely
"baseless"
"battlegrounds"
"by
"complete
"constructive"
"crimes
"decisive
"deep
"destructive"
"devastation"
"disappointed"
"drastically"
"embarrassment",
"expanded"
"failed"
"flagrant
"foreign
"gay
"grow
"height
"hunting
"invisible",
"job
"major
"mature"
"monopoly"
"not
"one
"probing"
"real
"realistic,
"reasonable"
"safe"

### Many titles in fake news dataset contain '#' before words which is not present in true news dataset. So, I will remove all the '#'.

In [35]:
# Removing the '[video]', ')','Watch:' as many fakeNewsTitle have these in the end

for i in range(len(fakeNewsTitle)):
    title = fakeNewsTitle[i]
    
    title = (title
             .replace("Watch:", "")
             .replace("Breaking:", "")
             .replace("Busted:", "")
             .replace("[video]", "")
             .replace("#", "")
             .replace(")", ""))

    title = " ".join(title.split())
    fakeNewsTitle[i] = title

### Saving the modified true and fake datasets

I am labelling trueNews to 1 and fakeNews to 0.

In [39]:
fakeNewsISOT = pd.DataFrame({
    "title" : fakeNewsTitle,
    "text": fakeNewsText,
    "authenticity": 0
        })

trueNewsText = trueNews['text']

trueNewsISOT = pd.DataFrame({
    "title" : trueNewsTitle,
    "text": trueNewsText,
    "authenticity" : 1
        })

In [40]:
fakeNewsISOT.to_csv("../data/processed/fakeNewsISOT.csv",index=False)
trueNewsISOT.to_csv("../data/processed/trueNewsISOT.csv",index=False)

### Now I will save the random mix dataset of fakeNewsISOT and trueNewsISOT to build the model for detection.

In [41]:
combineNews = pd.concat([fakeNewsISOT,trueNewsISOT], ignore_index=True)
NewsISOT = combineNews.sample(frac=1,random_state=42).reset_index(drop=True)

In [42]:
NewsISOT.to_csv('../data/processed/NewsISOT.csv',index=False)

In [43]:
NewsISOT.head(30)

,title,text,authenticity
0,Clinton's lead over Trump narrows to 9 points:...,Democratic presidential hopeful Hillary Clinto...,1
1,photo Of terrorist Who threatened to kill 16 “...,This is not a joke. I am to do my part to rid ...,0
2,Trump seeks legislative wins to cast off shado...,President Donald Trump pressed Republican cong...,1
3,Jason Chaffetz prepares to run for The hills A...,"Earlier this year, Jason Chaffetz, the House O...",0
4,EU's Juncker says ready to retaliate if needed...,The European Union’s chief executive on Wednes...,1
5,Trump screams at The Top Of his lungs About Hi...,Donald Trump hasn t even secured the nominatio...,0
6,Trump-supporting gun nut holds ar-15 like a ba...,Gun nuts are a strange breed. They are paranoi...,0
7,Trump rally makes stock options great again fo...,Donald Trump once described Jamie Dimon as “th...,1
8,Just in: Trump just spoke out on fate Of UCLA ...,President Trump just spoke out on the fate of ...,0
9,Trump bans The Public From calling The White H...,In another attempt to stifle freedom of expres...,0
10,Bravo! legendary civil rights leader takes hea...,Decades ago he stood against oppression by sit...,0
11,MSNBC host has perfect response to coughing go...,Ever since Democratic nominee Hillary Clinton ...,0
12,This IS huge! Trump suspends expedited h1-b vi...,WASHINGTON DC Foreigners aiming for temporar...,0
13,Spanish government says Catalan response not v...,The response from Catalonia s leader on Monday...,1
14,This picture of harriet tubman should Be used ...,Obama has filled his cabinet with radical yes...,0
15,Keith olbermann to Betsy devos: “the Hurricane...,The lefty lunatic of the day just can t keep h...,0
16,Judge rules: Obama White House showed ‘bad fai...,A judge just told us all what we ve known for ...,0
17,Holy tax plan! Bernie Sanders released his Pla...,Hey Bernie fans! You might want to take a look...,0
18,U.S. anti-bias law does not protect transgende...,The U.S. Department of Justice has reversed co...,1
19,Trump: ex-adviser Flynn should seek immunity i...,U.S. President Donald Trump on Friday backed a...,1
20,Tillerson says does not agree with Trump comme...,U.S. Secretary of State nominee Rex Tillerson ...,1
21,Delegate Plan to block Trump is concrete and i...,"For the last few weeks, rumors have been swirl...",0
22,Russian submarine fires cruise missiles at Isl...,A Russian submarine on Tuesday fired cruise mi...,1
23,Latino trump supporter: “it was harder to come...,This guy is great! He describes how it was to ...,0
24,Japan to expand ballistic missile defense with...,Japan formally decided on Tuesday it would exp...,1
25,"Get used to drills, China tells Taiwan; Taipei...",Taiwan will gradually get used to Chinese air ...,1
26,Ted Cruz About to reintroduce failed pro-hate ...,"Barring something completely unforeseen, Donal...",0
27,What were ex-Trump adviser Bannon's policy win...,President Donald Trump on Friday fired his chi...,1
28,Activists brilliantly troll chickenhawk Trump ...,Astute CBS reporter Rebecca Shabad couldn t po...,0
29,"Singapore minister says he, and his colleagues...",One of the contenders to be Singapore s next l...,1

In [44]:
NewsISOT.info()

<class 'pandas.DataFrame'>
RangeIndex: 38214 entries, 0 to 38213
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         38214 non-null  str
 1   text          38214 non-null  object
 2   authenticity  38214 non-null  int64
dtypes: int64(1), object(1), str(1)
memory usage: 895.8+ KB